# Generated by Django 4.2.9 on 2024-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
