# Generated by Django 4.2.9 on 2024-02-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categorymodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='id',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='categoryid',
            field=models.CharField(default='PR001', max_length=30, primary_key=True, serialize=False),
        ),
    ]
